package com.example.pruebatheming.designsystem.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// - BerlinLightTheme
val berlinPrimaryLight = Color(0xFF415F91)
val berlinOnPrimaryLight = Color(0xFFFFFFFF)
val berlinPrimaryContainerLight = Color(0xFFD6E3FF)
val berlinOnPrimaryContainerLight = Color(0xFF001B3E)
val berlinSecondaryLight = Color(0xFF565F71)
val berlinOnSecondaryLight = Color(0xFFFFFFFF)
val berlinSecondaryContainerLight = Color(0xFFDAE2F9)
val berlinOnSecondaryContainerLight = Color(0xFF131C2B)
val berlinTertiaryLight = Color(0xFF705575)
val berlinOnTertiaryLight = Color(0xFFFFFFFF)
val berlinTertiaryContainerLight = Color(0xFFFAD8FD)
val berlinOnTertiaryContainerLight = Color(0xFF28132E)
val berlinErrorLight = Color(0xFFBA1A1A)
val berlinOnErrorLight = Color(0xFFFFFFFF)
val berlinErrorContainerLight = Color(0xFFFFDAD6)
val berlinOnErrorContainerLight = Color(0xFF410002)
val berlinBackgroundLight = Color(0xFFF9F9FF)
val berlinOnBackgroundLight = Color(0xFF191C20)
val berlinSurfaceLight = Color(0xFFF9F9FF)
val berlinOnSurfaceLight = Color(0xFF191C20)
val berlinSurfaceVariantLight = Color(0xFFE0E2EC)
val berlinOnSurfaceVariantLight = Color(0xFF44474E)
val berlinOutlineLight = Color(0xFF74777F)
val berlinOutlineVariantLight = Color(0xFFC4C6D0)
val berlinScrimLight = Color(0xFF000000)
val berlinInverseSurfaceLight = Color(0xFF2E3036)
val berlinInverseOnSurfaceLight = Color(0xFFF0F0F7)
val berlinInversePrimaryLight = Color(0xFFAAC7FF)
// - BerlinDarkTheme
val berlinPrimaryDark = Color(0xFFAAC7FF)
val berlinOnPrimaryDark = Color(0xFF0A305F)
val berlinPrimaryContainerDark = Color(0xFF284777)
val berlinOnPrimaryContainerDark = Color(0xFFD6E3FF)
val berlinSecondaryDark = Color(0xFFBEC6DC)
val berlinOnSecondaryDark = Color(0xFF283141)
val berlinSecondaryContainerDark = Color(0xFF3E4759)
val berlinOnSecondaryContainerDark = Color(0xFFDAE2F9)
val berlinTertiaryDark = Color(0xFFDDBCE0)
val berlinOnTertiaryDark = Color(0xFF3F2844)
val berlinTertiaryContainerDark = Color(0xFF573E5C)
val berlinOnTertiaryContainerDark = Color(0xFFFAD8FD)
val berlinErrorDark = Color(0xFFFFB4AB)
val berlinOnErrorDark = Color(0xFF690005)
val berlinErrorContainerDark = Color(0xFF93000A)
val berlinOnErrorContainerDark = Color(0xFFFFDAD6)
val berlinBackgroundDark = Color(0xFF111318)
val berlinOnBackgroundDark = Color(0xFFE2E2E9)
val berlinSurfaceDark = Color(0xFF111318)
val berlinOnSurfaceDark = Color(0xFFE2E2E9)
val berlinSurfaceVariantDark = Color(0xFF44474E)
val berlinOnSurfaceVariantDark = Color(0xFFC4C6D0)
val berlinOutlineDark = Color(0xFF8E9099)
val berlinOutlineVariantDark = Color(0xFF44474E)
val berlinScrimDark = Color(0xFF000000)
val berlinInverseSurfaceDark = Color(0xFFE2E2E9)
val berlinInverseOnSurfaceDark = Color(0xFF2E3036)
val berlinInversePrimaryDark = Color(0xFF415F91)


// - JacketLightTheme
val jacketPrimaryLight = Color(0xFF8F4C38)
val jacketOnPrimaryLight = Color(0xFFFFFFFF)
val jacketPrimaryContainerLight = Color(0xFFFFDBD1)
val jacketOnPrimaryContainerLight = Color(0xFF3A0B01)
val jacketSecondaryLight = Color(0xFF77574E)
val jacketOnSecondaryLight = Color(0xFFFFFFFF)
val jacketSecondaryContainerLight = Color(0xFFFFDBD1)
val jacketOnSecondaryContainerLight = Color(0xFF2C150F)
val jacketTertiaryLight = Color(0xFF6C5D2F)
val jacketOnTertiaryLight = Color(0xFFFFFFFF)
val jacketTertiaryContainerLight = Color(0xFFF5E1A7)
val jacketOnTertiaryContainerLight = Color(0xFF231B00)
val jacketErrorLight = Color(0xFFBA1A1A)
val jacketOnErrorLight = Color(0xFFFFFFFF)
val jacketErrorContainerLight = Color(0xFFFFDAD6)
val jacketOnErrorContainerLight = Color(0xFF410002)
val jacketBackgroundLight = Color(0xFFFFF8F6)
val jacketOnBackgroundLight = Color(0xFF231917)
val jacketSurfaceLight = Color(0xFFFFF8F6)
val jacketOnSurfaceLight = Color(0xFF231917)
val jacketSurfaceVariantLight = Color(0xFFF5DED8)
val jacketOnSurfaceVariantLight = Color(0xFF53433F)
val jacketOutlineLight = Color(0xFF85736E)
val jacketOutlineVariantLight = Color(0xFFD8C2BC)
val jacketScrimLight = Color(0xFF000000)
val jacketInverseSurfaceLight = Color(0xFF392E2B)
val jacketInverseOnSurfaceLight = Color(0xFFFFEDE8)
val jacketInversePrimaryLight = Color(0xFFFFB5A0)

// - JacketDarkTheme
val jacketPrimaryDark = Color(0xFFFFB5A0)
val jacketOnPrimaryDark = Color(0xFF561F0F)
val jacketPrimaryContainerDark = Color(0xFF723523)
val jacketOnPrimaryContainerDark = Color(0xFFFFDBD1)
val jacketSecondaryDark = Color(0xFFE7BDB2)
val jacketOnSecondaryDark = Color(0xFF442A22)
val jacketSecondaryContainerDark = Color(0xFF5D4037)
val jacketOnSecondaryContainerDark = Color(0xFFFFDBD1)
val jacketTertiaryDark = Color(0xFFD8C58D)
val jacketOnTertiaryDark = Color(0xFF3B2F05)
val jacketTertiaryContainerDark = Color(0xFF534619)
val jacketOnTertiaryContainerDark = Color(0xFFF5E1A7)
val jacketErrorDark = Color(0xFFFFB4AB)
val jacketOnErrorDark = Color(0xFF690005)
val jacketErrorContainerDark = Color(0xFF93000A)
val jacketOnErrorContainerDark = Color(0xFFFFDAD6)
val jacketBackgroundDark = Color(0xFF1A110F)
val jacketOnBackgroundDark = Color(0xFFF1DFDA)
val jacketSurfaceDark = Color(0xFF1A110F)
val jacketOnSurfaceDark = Color(0xFFF1DFDA)
val jacketSurfaceVariantDark = Color(0xFF53433F)
val jacketOnSurfaceVariantDark = Color(0xFFD8C2BC)
val jacketOutlineDark = Color(0xFFA08C87)
val jacketOutlineVariantDark = Color(0xFF53433F)
val jacketScrimDark = Color(0xFF000000)
val jacketInverseSurfaceDark = Color(0xFFF1DFDA)
val jacketInverseOnSurfaceDark = Color(0xFF392E2B)
val jacketInversePrimaryDark = Color(0xFF8F4C38)