name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Gradle Test
        run: ./gradlew testDebugUnitTest --rerun-tasks --stacktrace

      - name: Generate failure report if required
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: common/build/reports/tests/testDebugUnitTest/